# Generated by Django 6.1.1 on 2026-09-12 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('project_created', 'created the project'), ('member_added', 'added a member'), ('member_removed', 'removed a member'), ('member_role_changed', 'changed a member role'), ('column_created', 'created a column'), ('task_created', 'created this task'), ('task_updated', 'updated this task'), ('task_moved', 'moved the task'), ('task_assigned', 'was assigned to this task'), ('task_unassigned', 'was unassigned from this task'), ('task_status_changed', 'changed the status'), ('task_priority_changed', 'changed the priority'), ('task_completed', 'completed this task'), ('comment_added', 'commented on this task')], max_length=40)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tasks.task')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='activity_ac_project_0d9dc1_idx'), models.Index(fields=['task', '-created_at'], name='activity_ac_task_id_7a5790_idx')],
            },
        ),
    ]
