# Generated by Django 6.1.1 on 2026-09-12 14:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='location',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
